os: linux
#dist: trusty

# sudo: false instructs Travis to build our project in a docker VM (faster)
sudo: required

# language: instructs travis what compilers && environment to set up in build matrix
language: cpp

# only available on private builds
cache:
 - apt

# Travis CI clones repositories to a depth of 50 commits
git:
  depth: 3

env:
  matrix:
    - VER_RELEASE='latest-alpha'  VER_MAJOR='3' VER_MINOR='2' VER_SUFFIX='alpha'
    - VER_RELEASE='latest-beta'   VER_MAJOR='3' VER_MINOR='1' VER_SUFFIX='beta'
    - VER_RELEASE='latest-rc'     VER_MAJOR='3' VER_MINOR='1' VER_SUFFIX='rc'    
    - VER_RELEASE='latest-stable' VER_MAJOR='3' VER_MINOR='1' VER_SUFFIX=''     

notifications:
  email:
    recipients:
      # travis encrypt "ci@example.org" --add notifications.email.recipients
      secure: VNLhC/BISjjwYQsd8xjdgitfgHvfRMrxkNYE3WQbOKcBUpYYUe2DH7toRsD2GdB2SjrKB6Iov+fp4Um+xhOQfNRStb5M73UsIUJetQwvkz9bNVERafq9Nng8b03LcXynV5XjGov1sxKS7xF1j5CYWIrQpKkQ15WOgUKrAI0kNIbxhApuZ409OEGA2NwKACRKXE9l8MA0WZlYB/D+t2o1i/6AeLpodxLqUVHhMjaxwFmNUMkz4Kv91RULG5iAvut8rquetkPVm6xU3lgkc/AnyDKeQSBdzVvtjUGzivZ5EWFse22d2hWwd3m5tWTDevr0+kQ37snpVRQANJGTtMZDxbVKr+aDC5Lm+CcVQaqES1EqWKYZypHlYDGjzb/zPQBkK3gFvuDeGLlYoVSjSXsmxN/Mrpik2S/kQlnDgeNbGohFW2+zNLOm5/Sp/7yiDt4ffFzz6X0wHQf49jX9wSA/x7PolWGCJJVY0vX+aWgKPpIPKjZe0JT89NUbtp1YR/8Hhjvv9aJ+F1NF6Uc12CxEdw1X/xqbJHTWzZgKm30b4bdCK+l2xcCj+7+QKP4CRFcuQxGE5s3WNfzRjqbdlhT6Yu73HfP9UQCAA6W8eh6G3h1a8NbvBZcWPWn6Bkz8a5fI6v1oBC2wu8Qx9uGa3DRql9HEvLszT/tHdiYeAgADMZ8=
    on_success: change
    on_failure: always
  slack:
    secure: Zrtl2NF6+dd4e7boH5JICVhQWfWFTqx/o3qr/Wa8/Fai8TYalFdWOujvE/8KH7j3G31iZueZ7z2ZsAPh8/rIIMNfdIxJ87sU0Ke0PYQKy1rMs8SaI7jh+f/+/w5Iki046bAJWQZzyIEcW4VqrkL7m6Aq5cf72FkgikK7wtDEgqryTn4P6l7tE81U4JLew0+pmOnPOrmqVbgwW6ABQrqvlz2pssAvpJ+RqDBnKbnFovPhV66BCyvYGrIlnzjHjsKYYNQA0ZTdHTdz4uSohkG/qHKypMhmX1jusgIEVCrpgbRr9Xhm12WthgbUsp2Nq0F5V4ddnusWhjh6ncyMKON1qTTlA9rn0P/YaKnjIMHYFKQjonHzQJVVZiIuSnQ/Gp5JynSP0BVYnvewyxpV66kNIqA/ZHE4a2zFGA/YSDPYpIhtgCEJ4od1/BIJGvN0EhGBaPZKzacquugh43IdqARnwwXvWE7lkct0qZbvSJUrelhqolkuVdkgp3JRza4Oe+XZ61PcyvktdkE+px2JVxuVIEpeM+GrH9QC5N3cuwJAlHVwhyo2fQ9Ghazd/DILONBeR2yQs/yYVCgakhFtGP3ymmt5SRhj3uJ3wXMQ4iKdIa6UKflXKeaOsNZpZz3F65yhfcAHPsvhLmMQpCvcoxLuZLSi+kEJSsmo+/9guOQFiVs=

before_install:
   # workaround for an issue related with the default export of the CC environment variable on Travis
   # https://github.com/travis-ci/travis-ci/issues/4682
   # https://github.com/travis-ci/docs-travis-ci-com/commit/fbca7ce4
  - test -n $CC && unset CC 
  - sudo apt-get -qq update
  - sudo apt-get install -y docbook5-xml docbook-xsl-ns html2text xsltproc  scons zlib1g-dev libcppunit-dev
  - "./nsis-install.sh"

install:
 - wget http://unitexgramlab.org/releases/${VER_RELEASE}/source/Unitex-GramLab-${VER_MAJOR}.${VER_MINOR}${VER_SUFFIX}-source-distribution.zip && unzip Unitex-GramLab-${VER_MAJOR}.${VER_MINOR}${VER_SUFFIX}-source-distribution.zip

script:
  - makensis -VERSION
  - makensis -DANONYMOUS_BUILD -DVER_MAJOR=${VER_MAJOR} -DVER_MINOR=${VER_MINOR} -DVER_SUFFIX=${VER_SUFFIX} -DINPUT_BASEDIR=. unitex.nsi
